\c client1
TRUNCATE TABLE VHashMatrix;
TRUNCATE TABLE DiUnitRange;
TRUNCATE TABLE HashList;


\c server1
TRUNCATE TABLE U_PERSON_DATA;
TRUNCATE TABLE PERSON_SIGNATURE;


\c peer1
TRUNCATE TABLE V_PERSON_DATA;
TRUNCATE TABLE person_rc;
TRUNCATE TABLE PERSON_STATS;
TRUNCATE TABLE HashList;



\c client2
TRUNCATE TABLE VHashMatrix;
TRUNCATE TABLE DiUnitRange;
TRUNCATE TABLE HashList;


\c server2
TRUNCATE TABLE U_PERSON_DATA;
TRUNCATE TABLE PERSON_SIGNATURE;



\c peer2
TRUNCATE TABLE V_PERSON_DATA;
TRUNCATE TABLE person_rc;
TRUNCATE TABLE PERSON_STATS;
TRUNCATE TABLE HASHLIST;

\c client3
TRUNCATE TABLE VHashMatrix;
TRUNCATE TABLE DiUnitRange;
TRUNCATE TABLE HashList;


\c client4
TRUNCATE TABLE VHashMatrix;
TRUNCATE TABLE DiUnitRange;
TRUNCATE TABLE HashList;



\c client5
TRUNCATE TABLE VHashMatrix;
TRUNCATE TABLE DiUnitRange;
TRUNCATE TABLE HashList;


\c client6
TRUNCATE TABLE VHashMatrix;
TRUNCATE TABLE DiUnitRange;
TRUNCATE TABLE HashList;